### ISSUE TITLE
How can I ping and check the status of an IP ?

### ISSUE THREAD

**Issue by leovarmak** [mtakaki/cachet-url-monitor#15]
How can I ping and check the status of an IP ? I tried giving the IP Instead of the Website name, but it doesnt work

**Comment by mtakaki** [comment]
This plugin only verifies HTTP URLs, so it doesn't ping any IP. It sends an HTTP request and verifies the response.

Looking at cachet's [third-party integrations page](https://docs.cachethq.io/docs/addons), I couldn't find any plugin that provides what you're looking for.

**Comment by leovarmak** [comment]
Alright. If you get across any please ping me .
(only if you remember)

**Comment by mtakaki** [comment]
Will do!
