### ISSUE TITLE
Monitor Multple URLs

### ISSUE THREAD

**Issue by thetechgy** [mtakaki/cachet-url-monitor#16]
Is it currently possible to monitor multiple URL's? I've tried entering multiple URL's into the config.yml file using the same format as the single URL example, making sure that each has the correct component ID, but only 1 seems to be checked and updated.

**Comment by mtakaki** [comment]
Hi, this is under development and being tracked on issue #9. I've been too busy with other projects and I'm still trying to get this out.

I'm going to close this issue, as we already have an issue being used to track this.
