### ISSUE TITLE
Monitoring multiple servers

### ISSUE THREAD

**Issue by shaun-ba** [mtakaki/cachet-url-monitor#22]
Excuse my ignorance a little, is the idea here to run a virtualenv and a copy of this codebase/config for every server/component, or am i missing something?

**Comment by waltrinehart** [comment]
i monitor four sites with four separate docker containers.

**Comment by mtakaki** [comment]
The idea is exactly how @waltrinehart suggested. Or you can run the same source code (with the virtualenv) and multiple configuration yaml files. Just start separate processes for each configuration. I'm still working on supporting multiple servers ( #9 ).
