### ISSUE TITLE
threshold = ?

### ISSUE THREAD

**Issue by haydenjames** [mtakaki/cachet-url-monitor#24]
Is threshold a value in seconds? Or is threshold the number of times before check is marked as a failed?

Example threshold = 5 ...would this prevent changes to cachet until 5 failed checks?

thanks

**Comment by mtakaki** [comment]
Threshold is related to latency. So it's the threshold for latency to consider the URL unstable. As documented in the readme, the unit is in seconds.

**Comment by haydenjames** [comment]
hmm. Interesting. I had threshold set to **60**, still this incident was created:
"Latency above threshold: 1.1176 seconds"

Switched to another alternative also listed here: https://docs.cachethq.io/docs/addons

> units is in seconds

**Comment by haydenjames** [comment]
...

**Comment by mtakaki** [comment]
Do you still have a question regarding this, @haydenjames? I just came back here to answer you and I can't find your comments anymore.
