### ISSUE TITLE
Pushing latency as milliseconds

### ISSUE THREAD

**Issue by gn-ley** [mtakaki/cachet-url-monitor#38]
Usually status pages show the latency in ms.

Cachet can't convert the seconds to milliseconds, so url-monitor should be able to do that.

I'm suggesting a config param to switch to ms.

**Comment by mtakaki** [comment]
That's a reasonable request. I'll try get this in over the weekend.

**Comment by mtakaki** [comment]
It turns out I forgot the build has been broken. I gotta fix it first before I can merge my changes to support this.

**Comment by brianjking** [comment]
@mtakaki Any update on this by chance? Thanks!

**Comment by mtakaki** [comment]
Sorry, I haven't had time to work on this project. I'll try getting it fixed asap.

**Comment by mtakaki** [comment]
This should be done now. I'm going to close this ticket. Please, feel free to reopen it if there's any issue or misunderstanding of this feature.
