### ISSUE TITLE
Running as python daemon

### ISSUE THREAD

**Issue by captainhook** [mtakaki/cachet-url-monitor#41]
I'm currently utilising screen to keep scheduler.py running in the background, but what would be great is to run as python daemon.

Has anyone managed to do this? There is some information on this [here](https://stackoverflow.com/questions/2975624/how-to-run-a-python-script-in-the-background-even-after-i-logout-ssh).

**Comment by mtakaki** [comment]
Do you have the option of running it as a docker container? You could also run it under kubernetes.

**Comment by mtakaki** [comment]
Great! That's definitely a better option. :)
I'm gonna close this ticket.
