### ISSUE TITLE
docker-compose file

### ISSUE THREAD

**Issue by PeterHsieh** [mtakaki/cachet-url-monitor#47]
Hello!

I'm attempting to set up an instance using Docker, and the README suggests that there is a docker-compose file ready for use, however, I can't seem to locate it. Is it meant to be in the repo?

**Comment by PeterHsieh** [comment]
#44 It looks like the dockerfile was removed in this commit. Not sure if it was intentional.

**Comment by mtakaki** [comment]
I've removed the docker-compose file because it wasn't working properly anymore. Cachet has a dependency on having a postgres database running. I'll update the README.

**Comment by jesobreira** [comment]
Any update on this?

**Comment by sadortun** [comment]
@mtakaki can you add the Docker compose file ?

**Comment by sadortun** [comment]
@mtakaki Can you update the readme?

**Comment by mtakaki** [comment]
I updated the README. Hopefully this is enough to close this ticket. Please, feel free to re-open it if you have any issue running this with docker. I don't want to maintain the docker-compose file, as it relied on the dockerized version of cachet and it brought some issues.

**Comment by boonisz** [comment]
Hi all,
I worked on a docker-compose for Cachet with cachet-url-monitor plugin.
The repo is: [cachet-url-monitor-dc](https://github.com/boonisz/cachet-url-monitor-dc)
Hope it can help ;)

**Comment by mtakaki** [comment]
Thanks for sharing it, @boonisz. Would you mind if I add a note about it in the README and link to it?

**Comment by boonisz** [comment]
With pleasure :)
