### ISSUE TITLE
InsecurePlatformWarning

### ISSUE THREAD

**Issue by arcreigh** [mtakaki/cachet-url-monitor#53]
InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

Running this from a shared hosting site, what is the minimum version requirement for this script? We are on python 2.6 atm.

**Comment by mtakaki** [comment]
This was written in python 2.7. I haven't tried running on 2.6. Could you please try running with 2.7?

**Comment by mtakaki** [comment]
Can I close this ticket? I haven't heard from you in 23 days...
