### ISSUE TITLE
The URL is unreachable

### ISSUE THREAD

**Issue by a-w11** [mtakaki/cachet-url-monitor#55]
Why this page is unreachable when it's reachable on browser? I paste log from console. When i add site like google.com it's work.

cachet:
  action:
  - CREATE_INCIDENT
  - UPDATE_STATUS
  api_url: ***
  component_id: 1
  public_incidents: true
endpoint:
  allowed_fails: 0
  expectation:
  - status_range: 200-300
    type: HTTP_STATUS
  - threshold: 10
    type: LATENCY
  - regex: .*(<body).*
    type: REGEX
  method: GET
  timeout: 10
  url: http://wnuk.it
frequency: 30
latency_unit: ms

     INFO [2018-09-23 00:39:18,235] cachet_url_monitor.configuration.Configuration - Monitoring URL: GET http://wnuk.it
     INFO [2018-09-23 00:39:18,236] cachet_url_monitor.configuration.Configuration - Registered expectation: 'HTTP status range: (200, 300)'
     INFO [2018-09-23 00:39:18,237] cachet_url_monitor.configuration.Configuration - Registered expectation: 'Latency threshold: 10.0000 seconds'
     INFO [2018-09-23 00:39:18,237] cachet_url_monitor.configuration.Configuration - Registered expectation: 'Regex: .*(<body).*'
     INFO [2018-09-23 00:39:18,237] cachet_url_monitor.scheduler.Scheduler - Registering action CREATE_INCIDENT
     INFO [2018-09-23 00:39:18,238] cachet_url_monitor.scheduler.Scheduler - Registering action UPDATE_STATUS
     INFO [2018-09-23 00:39:18,238] cachet_url_monitor.scheduler.Scheduler - Starting monitor agent...
  WARNING [2018-09-23 00:39:51,269] cachet_url_monitor.configuration.Configuration - The URL is unreachable: GET http://wnuk.it
     INFO [2018-09-23 00:39:51,270] cachet_url_monitor.configuration.Configuration - Failure #1 with threshold set to 0
     INFO [2018-09-23 00:39:51,312] cachet_url_monitor.configuration.Configuration - Incident uploaded, API unhealthy: component status [3], message: "The URL is unreachable: GET http://wnuk.it"

**Comment by mtakaki** [comment]
I'm closing this ticket as I haven't heard anything back. Please, feel free to reopen it if the issue is still happening.
