### ISSUE TITLE
CREATE_INCIDENT & UPDATE_STATUS on the same thread but one after the other - currently it overwrites!

### ISSUE THREAD

**Issue by psudoorg** [mtakaki/cachet-url-monitor#57]
Once the issue is reported (say, a downtime), can the uptime be reported as a separate message on the same thread?

Currently, it overwrites the downtime message and simply rewrites it with the uptime message.

Also, can we structure the schema to display as a chronological / timeline view?

**Comment by mtakaki** [comment]
I'm closing this issue as I haven't heard anything back in 22 days. Please, feel free to reopen it.
