### ISSUE TITLE
Check multiple URLs?

### ISSUE THREAD

**Issue by ogghi** [mtakaki/cachet-url-monitor#66]
Hi there, I really like this plugin! How could I go and check multiple URLs?
By using multiple config files? How could I load multiple config files?
Thanks
David

**Comment by mtakaki** [comment]
Sorry about the delay to answer you. Here's a solution proposed by @k1-hedayati
https://github.com/mtakaki/cachet-url-monitor/pull/58

**Comment by ogghi** [comment]
Hi @mtakaki  thanks for letting me know.
I tried the code from the other repo, but had no luck.
Any chance to merge this anytime soon?

**Comment by mtakaki** [comment]
Sorry, I really got swamped with other projects and only coming back to this now. I'll try merging these changes.

**Comment by mtakaki** [comment]
Thanks to @aberenshtein this is finally done.
