### ISSUE TITLE
 URL unavailable 

### ISSUE THREAD

**Issue by SamFreaks** [mtakaki/cachet-url-monitor#69]
Hey,i always become this error:

 URL unavailable 
`INFO [2019-07-11 17:04:03,217] cachet_url_monitor.configuration.Configuration - Monitoring URL: GET https://example.de/
     INFO [2019-07-11 17:04:03,217] cachet_url_monitor.configuration.Configuration - Registered expectation: 'HTTP status range: (200, 300)'
     INFO [2019-07-11 17:04:03,217] cachet_url_monitor.scheduler.Scheduler - Registering action CREATE_INCIDENT
     INFO [2019-07-11 17:04:03,217] cachet_url_monitor.scheduler.Scheduler - Registering action UPDATE_STATUS
     INFO [2019-07-11 17:04:03,217] cachet_url_monitor.scheduler.Scheduler - Starting monitor agent...
  WARNING [2019-07-11 17:04:33,245] cachet_url_monitor.configuration.Configuration - Request timed out
     INFO [2019-07-11 17:04:33,245] cachet_url_monitor.configuration.Configuration - Failure #1 with threshold set to 0
     INFO [2019-07-11 17:04:33,380] cachet_url_monitor.configuration.Configuration - Incident uploaded, API unhealthy: component status [2], message: "Request timed out"`

My config is:

`endpoint:
  url: https://example.de/
  method: GET
  #header:
    #SOME-HEADER: SOME-VALUE
  timeout: 0.01
  expectation:
    - type: HTTP_STATUS
      status_range: 200-300
    #- type: LATENCY
    #  threshold: 15
    #- type: REGEX
    #  regex: '.*(<body).*'
  allowed_fails: 0
cachet:
  api_url: https://status.example.de/api/v1
  token: my_token
  component_id: 1
  metric_id: 1
  action:
    - CREATE_INCIDENT
    - UPDATE_STATUS
  public_incidents: true
  latency_unit: s
frequency: 30
`

Edited url to example.de, dont post my real url here, also my token ;)

So what i am do wrong?

**Comment by mtakaki** [comment]
How are you running this tool? Through docker or directly running on a server? Can you check if you can hit the url? Sometimes, if using docker, it can have a different dns configuration and it can't resolve your URL, especially if it's internal.

**Comment by mtakaki** [comment]
I'm closing this ticket, as I haven't gotten an answer in 15 days. Please, feel free to re-open it if it's still happening for you.
