### ISSUE TITLE
How can I customize status and incident?

### ISSUE THREAD

**Issue by LucaTheHacker** [mtakaki/cachet-url-monitor#72]
Hi, I'm trying to edit my configuration, how can I edit the incident and the status?

**Comment by mtakaki** [comment]
You want to customize the incident and the status?

**Comment by LucaTheHacker** [comment]
Yes, like the incident message and maybe setting major outage and not partial

**Comment by mtakaki** [comment]
That's actually not configurable in the `config.yml`... In that case this would be a new feature request for both things: configuring the incident message and controlling the kind of status it would trigger.

**Comment by mtakaki** [comment]
I just published version 0.5 that includes this feature, to override the incident status. Unfortunately, customizing the message could be cumbersome. For example, the `HTTP_STATUS` expectation shows the status it got, while `REGEX` doesn't have any parameter in the string. Unless we let it be customizable, but remove the ability to pass parameters.
