### ISSUE TITLE
Component with id does not exist

### ISSUE THREAD

**Issue by dylie** [mtakaki/cachet-url-monitor#73]
Hello,

I'm getting the error 'Component with id does not exist.', are my settings wrong? Can the api read groups using your monitor? Or can't it be in groups?
![error](https://user-images.githubusercontent.com/38665633/68325073-0b865180-00c9-11ea-9313-ea8ad690fe8e.jpg)

**Comment by mtakaki** [comment]
Yeah, your API URL is incorrect. It should be `http://uptime.ether1.org/api/v1`. Could you please retry it if this URL (it shouldn't include `/components`)?

**Comment by dylie** [comment]
Same issue.. :/
![problem](https://user-images.githubusercontent.com/38665633/68543121-47643400-03b3-11ea-929a-3493bc71e31e.jpg)

**Comment by mtakaki** [comment]
Did you figure this out, @dylie? Are you still having issues?

**Comment by mtakaki** [comment]
I'm closing this issue. Please, feel free to reopen it if you're still facing this issue, @dylie
