### ISSUE TITLE
Self-Signed certificate

### ISSUE THREAD

**Issue by crak-mmarcoux** [mtakaki/cachet-url-monitor#87]
Hi getting this error
requests.exceptions.SSLError: HTTPSConnectionPool(host='cachetdocker_cachet_1', port=8000): Max retries exceeded with url: /api/v1/components/1 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1056)')))

Could it be avoided by doing the REQUEST variable?
Thanks
Math

**Comment by mtakaki** [comment]
Hi @crak-mmarcoux, yes, I believe so. You can see more context here: #46
The environment variable is `REQUESTS_CA_BUNDLE` and you need to point it at your ca bundle.

**Comment by crak-mmarcoux** [comment]
Looks ok! I opened a non-ssl page.

**Comment by mtakaki** [comment]
Thanks for confirming it, @crak-mmarcoux. Feel free to re-open it if you see it again.
