### ISSUE TITLE
latency_unit is read from cachet section

### ISSUE THREAD

**Issue by nijel** [mtakaki/cachet-url-monitor#89]
The code behaves differently than documented, the docs says, that `latency_unit` should be placed in endpoint configuration, but it is read from cachet section:

https://github.com/mtakaki/cachet-url-monitor/blob/ae0555cb705a6e5ed16d292ca8aaf638df2a0332/cachet_url_monitor/configuration.py#L86-L87

I can submit a PR once it's clear whether code or docs is the one to follow :-).

**Comment by mtakaki** [comment]
Good catch! The configuration should be per endpoint, as metrics are 1:1 with resources. I'll let you decide if you want to tackle this or should I do it :)
