### ISSUE TITLE
Support multiple URLs but with same expectations and under the same component

### ISSUE THREAD

**Issue by mtakaki** [mtakaki/cachet-url-monitor#9]
We should be able to support multiple URLs, as long as they all have the same expectation and falls under the same component.

**Comment by neggs** [comment]
Hi, thanks for the super plugin. Any news on the multi url request?

**Comment by mtakaki** [comment]
I'm sorry for the delay, @neggs. I've been swamped with other projects and I'm not happy with my current implementation for this. I'll try getting it done in the next weeks.

**Comment by ekim92** [comment]
Hi, any updates on multi-url?

**Comment by mtakaki** [comment]
This will require some refactoring. My first attempt was not good and it would be serial. If you had 100 URLs and each took 1s to check, it would take in total 100 seconds to verify all of them. So, instead I'm rewriting it to do it in parallel (with a cap on the number of threads). Just really didn't have time to get it done. This is still on top of my priorities.

**Comment by alaverty** [comment]
@mtakaki any progress? I would like to load up a number of different URL's, also is there a way to turn off SSL verification on https urls?

**Comment by ColdrickSotK** [comment]
@mtakaki In addition to this improvement, is there any interest in supporting monitoring multiple different URLs but with **different** expectations and component?

I know its currently possible to do that by running multiple instances of the monitoring process, but ideally I would like to not have to manage configuration in multiple different files.

I'm happy to look at sending a PR for it if you think its worthwhile.

**Comment by mtakaki** [comment]
This was fixed through #76. All thanks to @aberenshtein
