### ISSUE TITLE
is there any way to integrate with AWS Secret server 

### ISSUE THREAD

**Issue by devopssecautomation** [mtakaki/cachet-url-monitor#99]
API keys we provide in config.yaml  need to integrate with AWS  secret server . for any cloudified environment where the central secret server is the only option to store keys, the current  version has the limitation. I appreciate it if anyone takes up this feature to develop.

**Comment by mtakaki** [comment]
Thanks for the suggestion, @devopssecautomation. I haven't actually considered it, but I'll see if I can get it implemented. Any help is more than welcome.

**Comment by mtakaki** [comment]
@devopssecautomation I've done some refactoring and added token providers. This is just the first step to implement this. I'll try adding the AWS secrets manager provider, but no promises it will be done today.

**Comment by mtakaki** [comment]
@devopssecautomation, do you think you could pull this branch and give it a try? I just need to confirm it's working correctly. #102

**Comment by mtakaki** [comment]
I tested it myself and it seems to be working fine. I'll close the ticket, but please feel free to re-open if you think it's incorrect or it doesn't match what you would expect.
